config/routes.rb
PrviApp::Application.routes.draw do
  resources :comments
  resources :shoes
  devise_for :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :shoe
  belongs_to :user
  attr_accessible :content, :shoe_id, :user_id
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  has_many :comments
  attr_accessible :description, :name, :price, :size, :color, :photo

  has_attached_file :photo

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.save
    @shoe = @comment.shoe
    redirect_to @shoe
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_filter :authenticate_user! , :except => [:show, :index]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shoes }
    end
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])
    @comment = @shoe.comments.build
    #@comment.user_id = current_user.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/new
  # GET /shoes/new.json
  def new
    @shoe = Shoe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/1/edit
  def edit
    @shoe = Shoe.find(params[:id])
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(params[:shoe])

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render json: @shoe, status: :created, location: @shoe }
      else
        format.html { render action: "new" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shoes/1
  # PUT /shoes/1.json
  def update
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      if @shoe.update_attributes(params[:shoe])
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy

    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :shoe_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Shoe</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.content %></td>
    <td><%= comment.user_id %></td>
    <td><%= comment.shoe_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Shoe:</b>
  <%= @comment.shoe_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrviApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shoes/_form.html.erb
<%= form_for @shoe, :html => { :multipart => true } do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<h1>Listing shoes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Description</th>
    <th>Price</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shoes.each do |shoe| %>
  <tr>
    <td><%= shoe.name %></td>
    <td><%= shoe.size %></td>
    <td><%= shoe.description %></td>
    <td><%= shoe.price %></td>
    <td><%= shoe.color %></td>
    <td><%= link_to 'Show', shoe %></td>
    <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
    <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shoe', new_shoe_path %>

app/views/shoes/new.html.erb
<h1>New shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>

<p>
  <b>Name:</b>
  <%= @shoe.name %>
</p>

<p>
  <b>Size:</b>
  <%= @shoe.size %>
</p>

<p>
  <b>Description:</b>
  <%= @shoe.description %>
</p>

<p>
  <b>Price:</b>
  <%= @shoe.price %>
</p>
<p>
  <b>Color:</b>
  <%= @shoe.color %>
</p>
<p>
  <b>Slika:</b>
  <%= image_tag @shoe.photo.url %>
</p>
<h2>New comment</h2>
<%= render 'comments/form' %>
<h2>Comment list</h2>
<% @shoe.comments.each do |comment| %>
    <div>
     <%= comment.content %>
    </div>
<% end %>